### ISSUE TITLE
코드 분석

### ISSUE THREAD

**Issue by Onewoo** [Onewoo/MaskRadar#2]
코드 분석중입니다.

**Comment by Onewoo** [comment]
핵심파일 누락 발견

**Comment by Onewoo** [comment]
개발자에게 메일 문의 넣음

**Comment by glass1222** [comment]
string.xml 없음

**Comment by glass1222** [comment]
res 쪽 font 폴더도 추가해줘야 함. 글꼴은 그대로 다운받아서 쓰자
짜잘한 @font/hanna_11yrs같은 그냥 누락된 오류가 많음

**Comment by Onewoo** [comment]
메일 문의 결과, 파일 몇가지 누락하고 fork했다고 알림

**Comment by Onewoo** [comment]
새로 개발해야하므로 새로 준비하는 데 약 9일 소요
